language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - liaolangsheng@163.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: XDdpruhmQFUBIe81UdiUTmuCyyf95feGgieV3114PzxiowFp3A1GNhVd/N/QsFxplLTxpER5vW84ih0Bv3EYs0dos40nCzW28jzUfsxW2SgtCU01MHHF0i38HxZHm/WP8B0CHsIAuRXnGJnsm3DL8rd6apSiGVkipD8Aj/QfnFQMko7Y2niLOEJIzl4RwNfk+ywrFJ72N3NuSJ92LmNS2hzKxNz2Hj5q/+BxGpCpuLcJyZOrBMcyfIFNvXc85TlX6pSHvIgzYA9rNysEZrknO3Ei5cIbnC5Aw5ua7lcMPdiKhq7E0S41nlsNjlJXczoaA0OOmrPe2lX3FHSMgHtrtiewS/lfhmgmrHD8xQdHuSQGcatZw2fWpJoFAv3CYVAvxDqZtyc/kXy8gCqq0alKvsD4PA6WsHemeD/qfmuyDsmtAIbZLtRv3SuY+HpCIhP4HxPCaxQ9rNx9VtRXn9hy9NaH27nLcsOlwB3zbBzy8juOB/BVaZ7AKN0g4wMnNoNJRgsXk02rcwLuUwyj9WNfDp1lGhzudRdHNuxd8VvcS21iqrKHCnpSuHTUlOUYe5RbGtX5/mOzi5WCKkrorreT0587HwMWzkZ4FkDlIjFfCWdGviSi/40b0BtIzlmEJOXinPHXXsRi1xxuzV4j27/Md2E/NVX62esz/eq2om8GTOY=
  - secure: dgiwAWostpafaGcXG4w9/uBGc4+TfJPVA6GievVZklmQJTcS2Ee/cSF6tAPpTI4XVdffPA1JekRdL2AuLpNum/iM+PLtwoUsMuz70E2qqnmvRpR+lbhqkZ6v1Pa4WO+H8EwoGT+GU6kBI619L8cPy3geVC1paAfxfcFJALe0xCLJn3UGm0lJSRSpTl7fAaNyqwQDdWSbddYK7xP7Ksp7fC1DaGLI7z90ujiPHouASLGFVEf+hFxmQRrxkMfTEtXXFbqz9OursXeR2/srSnBA092l4qI7iwJUzhWrpWRF3epbV9f7aZB3TuK1vs5UMG/Sxp90J5bxR+Hkl1cLjShkXbvafrVxSbV4xyHyOvDWgAlHAEPzAcqm7srZs0h2BEYoVjT3tIVpw8FAxxmyOGhx2qfI4I4egzhSZPUkxnXDiGq8p6egPlRn7Dv5pxD2efwCycRA+gcAWaquESGu+JZi1vzyrs/rIl09aA8y24htQA5NkPhUkUf12VyJ0XDPVD4ZV+X+yyOhoiFwaQQ2yirqlD6fwsSJgNiQjg608GW9QweZ0+LuQe81+6dbUGL9SbME8EjkqeB9j8AwlC6HHLPUU4Dm0I4Edovsh7Lp+sXOKap6o6VDwnQif2nxpDQGkvSFpJnBQiNYdkC7DpqdrBj63BLrkYVYDwLQjyBR8zjpGJE=
  - secure: NJ+B6cuuB0+mqztAUiOWxSa9FbLuTTYzZ0ISR5UwWXubk+w1ijr5mAAaWAu1ofHMgR+LRAxVpKxgrHokSoEIcJjoXOTSa7sziA5a33NmShUR0o6r8+m9okg4/IkMzpnHzGmtDQvGrIHSSJXLDQeLnUPyO4vnjQ8dG+yVp8ow8spXQNnwtY7W11awzriw/txxaTBf5XKaebcEIyQDZZeyAe0dxW/O5V1KlQf7b6fal2s6uwhTYlVhtkVbuca2+FgC7wmnu2x4HfTnOMJPfm57+vlg754otYSuG56QKE42CKL0jXAxHfxInVxyfwbfHyjh1p27a1S6F8np5w+uKx7dMIQ9ZhZwPwbeKS+nzIIS64KsBm40smYkw+Uk/wHi41XhJtwY31I4HCWiYyrV8d8csp9RnZpcHWNYa1ONLoanljOD9jkdwfGrEjqtt8c5FyRzgkgJdywB82GE8ovdjLB6ky+n9+OmsdoVv+poksEIObLIoMV/qK6P2fpRHLSFCSmmrmiJsu4kZ4A6zST6z92x4mcQxatt223lBWQzF/iXWbQqS6KuZeuA7FRCFPu+YFfkExgFmDhhgwzj3WUpHRyMP7Z0h5RQv+PtmBoOKT75ebUzQ0C0gss6wZUnMGsnLcXYzlaSBAVvlmMfI0rA3MC0JAs4SF4yfmvWstPfy1nBycg=
before_install:
- chmod +x mvnw
- export BUILD_NAME=deploy-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
