language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - liaolangsheng@163.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  
