language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - liaolangsheng@163.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: AyKHTIbP6p5ynR8nkFaw3lYOUJSdUltShlrZL7d7movBE/UEGJMUOyImV6+rS0RCM3JP1UQAk56EsNRtuOsB1t9gqBxGgRQdAwmupKGb9xhhkGF7qsaHNykVca1qDHrbVLis59HXHwT/tILDzT9gwmS3AuHM7Dxb+6IfJIXSAwDVDpSpFVAxTj2qvx676ibf0WNc2zr+DO7Sg5FaASMe4wdohOPvA6qvbjEMDtBVzCS5LJXZ4hZyS4EUX788dVvIDRXGyIyfL/55ntZwvtmlELFoTWKHT0E7+Nq+bB5uiJSELlYzG0HSZtvxd3jGD7h7XeGve1v994fxuNflxWW2wlTCYCiednUasEDFPHzkM3C2J4SYnQSiRKfxFHSKkYKQiidNWXG+3nNImhA7JOd05qBe1cgg99n8B4tzA4ybph5NtzFVBKnPmPctlfMS64Qj3g1gZ+9djsDf7HmDc3hTykJldRraVpGmAXSxILl9H774KlVisqZ0Gg3bliYvJz92n0Mbt2mmagCQq0nzQCqSyP0PSoREe8+m99FTdrLEQb7vhRkT+o8ELwycnq+45gCO1Yf4x64rYC/cJ4PZBnvFnNJSwncw/cjZ3KdXV87vY0DuUYkhHNuV2hF7OGoUQkUKEcbUUaJdFqilF3vZm88ldA5F22H7yER/bVoTcHppOL0=
  - secure: bUZ1yWdHFcQ+xobvRi3iRSXM4IJNGT+IfhhCT3zgcmFKfiRgxx1+kTpJRVT9dxbO/kX1oMrNtPBJ4m1TUtOdy3te5aEZ+e6NwAc/07i/zr3aDtjwuO2sUkRtbTl0eCPDM99uW4gUaqfkOL3lMWO4X/SaTZ8FSyiA0p5zIZGnEakD/RWxRi2xTryY1UN9pBKM1aYgqMTRGo0fmnQRhfesES1XAzEGt7Cye1xoCnsFc36AI+eii1T/XWwlaVGT8Jbs5xg7DvGMCfI+IeQjQ9fcC406mItBthkOry8lmsH+hWU49J3Vp+NAwE/ESkdSQFppA4++0WaQbKyOH+l5bIZZ7giAjmKI8xK7Kcx0xEd1w9kdWPE+7sSZYndu1BNlKwPMBRxabYU4PwK6WVW9JqPNs2z+ehyUU1xw805XO43C2Pmp3SO2RekHRPz6QoE4G7X4inkpgwrjcmAKd+eRs8P6UwcPioEt2h/gTZ42QF0e4bvpfzRBfl3mUErFFMvWReYSmnqQbWQQUwGDsyFxrW+G4t8G1RopsHpE2k0i+b6VzkfcDHWCoVZBKyWmzaeKuajIUpyQGy1CDWvZVJvaK3cpyXL9/Mlg7wI+A36DRdUErAZEBxXJKt4sbyQtskW1Fw3rTYn3w/OJXAYZZsUGFDyrJXfpD32zu3kVTPwl6+Oy+xQ=
  - secure: kTXc+hmw7XgXopOnqJSBle7/jXFcU0IG1f4mKaA15VyLwWsnWv/oZAk1G2TauQVu8/f/wBmEdS0xJupEjTBI54WZ8zDzU7FywysgSg81D/MaLjz7qrVxhsIrgipkFR/sbFxHBYnsMiXLXCfG1R8f9EAQ51OfR7Ish5SVqqBXA+tVMioYMjHHemUD/2MLx+O+BauHq5c6La4LesYzUODH+kk30rfKblVautFwrL8cx/sVIQjVc6nn1byLPWI3K0YOvnotOz02mVhTIlhOonc8FPil5SH3Zmpzovz1Hul6mTTh4Hhvlv3aEHukjWUwpdLYuUk0Mq5azRIqLytQVrnqNMJQLBbGhIbDEWDo1waWr/UEsOc9hrKsuExR+GFJLd2BACSZRqzj83kKJ6VBw8vPVhrxGrhge6uuaa42rqaGlIh9eC+tLXh3vVND/B2DJX33+h9CIc/XAefVBGMQgmS4k5AwnjWXMR2ROQ4gPQZ0avixlLz1i+Pm2Hd4H3Io1qR0xPCcs80TepWn/4UD9Wv3rviLhbuXoeS+GCT3tPq4hyz9o2WmEiGBGzrXMGlcyxgx/G7vDE9D537qS8/r694sJdUHesJVu1JuAu/ylnnfvnoRFC3GUgJp8cTFC9lAqvpy+H3cXUN9sQUBrdWD5bzKeNbv+AZNY6/4N+X0n9mGRfM=
before_install:
- gem install travis -v 1.8.5 --no-rdoc --no-ri
- export BUILD_NAME=deploy-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh